
CREATE TABLE PESSOA(
    ID_PESSOA        INT             NOT NULL,
    P_NOME        VARCHAR(20)     NOT NULL,
    U_NOME        VARCHAR(20)     NOT NULL,
    D_NASC        DATE            NOT NULL,
    IDADE            INT            NOT NULL,
    SEXO            CHAR(1)        NOT NULL,
    NACIONALIDADE    CHAR(3)        NOT NULL,

    CONSTRAINT PEPK
    PRIMARY KEY(ID_PESSOA)
);

CREATE TABLE JUIZ(
    ID_PESSOA        INT        NOT NULL,

    CONSTRAINT JZPK
    PRIMARY KEY(ID_PESSOA),

    CONSTRAINT JZFK
    FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
        ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE ATLETA(
    ID_PESSOA        INT        NOT NULL,
    SIGLA_PAÍS        CHAR(3)    NOT NULL,

    CONSTRAINT ATPK
    PRIMARY KEY(ID_PESSOA),

    CONSTRAINT ATFK1
    FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT ATFK2
    FOREIGN KEY(SIGLA_PAÍS) REFERENCES "paÍs"(sigla_pais)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PAIS(
    SIGLA_PAIS        CHAR(3)    NOT NULL,
    NOME_PAIS        CHAR(57)    NOT NULL,

    CONSTRAINT PAPK
    PRIMARY KEY(SIGLA_PAIS)
);

CREATE TABLE PROVA(
    ID_PROVA        INT        NOT NULL,
    ID_JUIZ        INT        NOT NULL,
    LOCALIZAÇÃO    CHAR(60)    NOT NULL,
    HORÁRIO        INT        NOT NULL,
    MODALIDADE    CHAR(60)    NOT NULL,
    TEMPO_RECORDE    INT,

    CONSTRAINT PRPK
    PRIMARY KEY(ID_PROVA),

    CONSTRAINT PRFK1
    FOREIGN KEY(ID_JUIZ) REFERENCES JUIZ(ID_PESSOA)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT PRFK2
    FOREIGN KEY(TEMPO_RECORDE) REFERENCES RECORDE(TEMPO)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OLIMPÍADA(
    ANO            INT        NOT NULL,
    SIGLA_PAÍS        CHAR(3)    NOT NULL,

    CONSTRAINT OLPK
    PRIMARY KEY(ANO),

    CONSTRAINT OLFK
    FOREIGN KEY(SIGLA_PAÍS) REFERENCES "paÍs"(SIGLA_PAIS)
        ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE MEDALHA(
    TIPO_MEDALHA    CHAR(6)    NOT NULL,
    ID_MEDALHA        INT        NOT NULL,

    CONSTRAINT MDPK
    PRIMARY KEY(ID_MEDALHA)
);

CREATE TABLE RECORDE(
    TEMPO    INT            NOT NULL,

    CONSTRAINT RCPK
    PRIMARY KEY(TEMPO)
);

CREATE TABLE TIMES(
ID_PROVA        INT        NOT NULL,
TIME            CHAR(60)    NOT NULL,

    CONSTRAINT TMPK
    PRIMARY KEY(ID_PROVA, TIME),

    CONSTRAINT TMFK
    FOREIGN KEY(ID_PROVA) REFERENCES PROVA(ID_PROVA)
        ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE VENCEDORES(
    ID_PROVA        INT        NOT NULL,
    VENCEDORES    CHAR(60)    NOT NULL,

    CONSTRAINT VNCPK
    PRIMARY KEY(ID_PROVA, VENCEDORES),

    CONSTRAINT VNCFK
    FOREIGN KEY(ID_PROVA) REFERENCES PROVA(ID_PROVA)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MODALIDADE(
    ID_ATLETA        INT        NOT NULL,
MODALIDADE    CHAR(60)    NOT NULL,

CONSTRAINT MDLPK
PRIMARY KEY(ID_ATLETA),

CONSTRAINT MDLFK1
FOREIGN KEY(ID_ATLETA) REFERENCES ATLETA(ID_PESSOA)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE REALIZA(
    ANO            INT        NOT NULL,
    ID_PROVA        INT        NOT NULL,

    CONSTRAINT RLZPK
    PRIMARY KEY(ANO, ID_PROVA),

CONSTRAINT RLZFK1
FOREIGN KEY(ANO) REFERENCES OLIMPÍADA(ANO)
    ON DELETE CASCADE ON UPDATE CASCADE,

CONSTRAINT RLZFK2
FOREIGN KEY(ID_PROVA) REFERENCES PROVA(ID_PROVA)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE GANHA(
    ID_ATLETA        INT        NOT NULL,
    ID_PROVA        INT        NOT NULL,
    ID_MEDALHA        INT        NOT NULL,

    CONSTRAINT GNHPK
    PRIMARY KEY(ID_ATLETA, ID_PROVA),

    CONSTRAINT GNHFK1
    FOREIGN KEY(ID_ATLETA) REFERENCES ATLETA(ID_PESSOA)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT GNHFK2
    FOREIGN KEY(ID_PROVA) REFERENCES PROVA(ID_PROVA)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT GNHFK3
    FOREIGN KEY(ID_MEDALHA) REFERENCES MEDALHA(ID_MEDALHA)
        ON DELETE CASCADE ON UPDATE CASCADE
);

